### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by maartendq** [OpenNebula/addon-terraform#8]
Hi,

When trying to build/install the addon, I get the following errors:

*src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_security_group.go:336:32: not enough arguments in call to sgc.Info
	have ()
	want (bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_template.go:198:26: not enough arguments in call to tc.Info
	have (bool)
	want (bool, bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_template.go:235:26: not enough arguments in call to tc.Info
	have ()
	want (bool, bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_template.go:246:26: not enough arguments in call to tc.Info
	have ()
	want (bool, bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_virtual_data_center.go:204:23: not enough arguments in call to vdcc.Info
	have ()
	want (bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_virtual_network.go:371:24: not enough arguments in call to vnc.Info
	have ()
	want (bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_virtual_network.go:710:48: not enough arguments in call to controller.Clusters().Info
	have ()
	want (bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_virtual_network.go:735:21: not enough arguments in call to vnc.Info
	have ()
	want (bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_virtual_network.go:846:21: not enough arguments in call to vnc.Info
	have ()
	want (bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_virtual_network.go:869:20: not enough arguments in call to vnc.Info
	have ()
	want (bool)
src/github.com/OpenNebula/addon-terraform/opennebula/resource_opennebula_virtual_network.go:869:20: too many errors*

It looks related to the .Info blocks in code and by adding "True" as argument, I can make the build work. I think it might be related to this commit in one code: https://github.com/OpenNebula/one/commit/9ed1d12dbb39514c1cc0d9cb111ea91f260398e8 .
You'll probably know better if decrypt boolean needs to be set to true or false, I assume true..

Br,
Maarten

**Comment by jaypif** [comment]
The PR: https://github.com/OpenNebula/addon-terraform/pull/10 has been merged and fix this issue.
